[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "java -Dspring.profiles.active=minimal -jar app.jar"
healthcheckPath = "/health"
healthcheckTimeout = 600
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"