[build]
builder = "NIXPACKS"

[build.nginx]
enable = false

[build.args]
BULD_COMMAND = "./gradlew clean bootJar -Pproduction -x test -x check"
START_COMMAND = "java -jar build/libs/inventory-system.jar"

[deploy]
startCommand = "java -jar build/libs/inventory-system.jar"