[build]
builder = "NIXPACKS"

[build.args]
JAVA_VERSION = "21"
JAVA_DISTRO = "temurin"  # Eclipse Temurin (Adoptium)
BUILD_COMMAND = "./gradlew clean bootJar -Pproduction -x test -x check"
START_COMMAND = "java -Dspring.profiles.active=prod -jar build/libs/inventory-system.jar"

[deploy]
startCommand = "java -Dspring.profiles.active=prod -jar build/libs/inventory-system.jar"