-- Initial schema creation for inventory system
-- This creates the basic table structure

-- Events table
CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_active BOOLEAN DEFAULT true
);

-- Products table
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    price NUMERIC(10,2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    can_be_personalized BOOLEAN DEFAULT false,
    has_variants BOOLEAN DEFAULT false
);

-- Product variants table
CREATE TABLE product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    variant_name VARCHAR(255) NOT NULL,
    sku VARCHAR(255),
    color VARCHAR(255),
    size VARCHAR(255),
    material VARCHAR(255),
    design VARCHAR(255),
    description VARCHAR(255),
    stock INTEGER NOT NULL DEFAULT 0,
    price_adjustment NUMERIC(10,2) DEFAULT 0.00,
    is_active BOOLEAN DEFAULT true,
    shopify_product_id VARCHAR(255),
    shopify_variant_id VARCHAR(255),
    CONSTRAINT fk_variant_product FOREIGN KEY (product_id) REFERENCES products(id)
);

-- Sales table
CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    sale_date TIMESTAMP NOT NULL,
    customer_name VARCHAR(255),
    customer_phone VARCHAR(255),
    customer_email VARCHAR(255),
    payment_method VARCHAR(255) NOT NULL,
    total_amount NUMERIC(10,2) NOT NULL,
    discount_amount NUMERIC(10,2) DEFAULT 0.00,
    tax_amount NUMERIC(10,2) DEFAULT 0.00,
    is_paid BOOLEAN DEFAULT false,
    is_cancelled BOOLEAN DEFAULT false,
    notes VARCHAR(255),
    CONSTRAINT fk_sale_event FOREIGN KEY (event_id) REFERENCES events(id)
);

-- Sale items table
CREATE TABLE sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    variant_id BIGINT,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL,
    total_price NUMERIC(10,2) NOT NULL,
    personalization VARCHAR(255),
    personalization_cost NUMERIC(10,2) DEFAULT 0.00,
    item_discount NUMERIC(10,2) DEFAULT 0.00,
    notes VARCHAR(255),
    CONSTRAINT fk_sale_item_sale FOREIGN KEY (sale_id) REFERENCES sales(id),
    CONSTRAINT fk_sale_item_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_sale_item_variant FOREIGN KEY (variant_id) REFERENCES product_variants(id)
);

-- Create indexes for better performance
CREATE INDEX idx_product_variants_product_id ON product_variants(product_id);
CREATE INDEX idx_sales_event_id ON sales(event_id);
CREATE INDEX idx_sales_date ON sales(sale_date);
CREATE INDEX idx_sales_payment_method ON sales(payment_method);
CREATE INDEX idx_sale_items_sale_id ON sale_items(sale_id);
CREATE INDEX idx_sale_items_product_id ON sale_items(product_id);
CREATE INDEX idx_sale_items_variant_id ON sale_items(variant_id);