-- Create brands table to manage product brands as a catalog
CREATE TABLE brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create trigger function to update updated_at column
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger for brands table
CREATE TRIGGER update_brands_updated_at 
    BEFORE UPDATE ON brands 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Insert default brands from existing products
INSERT INTO brands (name, description, is_active) VALUES
('Perro Amor', 'Marca principal de productos para mascotas', TRUE),
('Perra Madre', 'Línea premium de accesorios', TRUE);

-- Create index on name for faster lookups
CREATE INDEX idx_brands_name ON brands(name);

-- Create index on is_active for filtering active brands
CREATE INDEX idx_brands_active ON brands(is_active);